import java.util.Timer;
public class ISUgui extends javax.swing.JFrame {
    Timer t;
    Updater u;
    static PointGenerator pN1,pN2,pN3;
        public ISUgui() {
            initComponents();
            initObjects();
            txtres.setText(Game.ToString());
            
    }
    private void initObjects(){
        //for scheduled increments
        t = new Timer();
        //the increment itself
        u = new Updater();
        //connecting the task to the timer
        t.schedule(u, 0, 1000);
        //first point generator
        pN1 = new PGnormal(10, 1);
        pN2 = new PGnormal(300, 10);
        pN3 = new PGnormal(1200, 100);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIncrease = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnbuyG1 = new javax.swing.JButton();
        txtcostG1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnbuyG2 = new javax.swing.JButton();
        txtcostG2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnbuyG3 = new javax.swing.JButton();
        txtcostG3 = new javax.swing.JTextField();
        btndouble = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generic Idle Game");

        btnIncrease.setText("+1");
        btnIncrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncreaseActionPerformed(evt);
            }
        });

        jLabel1.setText("Resources:");

        txtres.setEditable(false);

        jLabel2.setText("Resource Generator #1 (+1/s)");

        btnbuyG1.setText("Buy");
        btnbuyG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuyG1ActionPerformed(evt);
            }
        });

        txtcostG1.setEditable(false);
        txtcostG1.setText("Initial Cost: 10");
        txtcostG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcostG1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Resource Generator #2 (+10/s)");

        btnbuyG2.setText("Buy");
        btnbuyG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuyG2ActionPerformed(evt);
            }
        });

        txtcostG2.setEditable(false);
        txtcostG2.setText("Initial Cost: 300");
        txtcostG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcostG2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Resource Generator #3 (+100/s)");

        btnbuyG3.setText("Buy");
        btnbuyG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuyG3ActionPerformed(evt);
            }
        });

        txtcostG3.setEditable(false);
        txtcostG3.setText("Initial Cost: 1200");
        txtcostG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcostG3ActionPerformed(evt);
            }
        });

        btndouble.setText("Double Click Power");
        btndouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoubleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIncrease)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndouble))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtres, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnbuyG2)
                                    .addComponent(btnbuyG3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(6, 6, 6))
                                    .addComponent(jLabel4))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnbuyG1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcostG2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcostG3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(txtcostG1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncrease)
                    .addComponent(btndouble))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnbuyG1)
                    .addComponent(txtcostG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnbuyG2)
                    .addComponent(txtcostG2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnbuyG3)
                    .addComponent(txtcostG3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncreaseActionPerformed
        //Manually click the button -> increase the resources by the amount
        //of the manual increase
        Game.increaseResources(ManualIncrease.incrementAmount);
        txtres.setText(Game.ToString());
        checkButtons();
    }//GEN-LAST:event_btnIncreaseActionPerformed

    private void btnbuyG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuyG1ActionPerformed
        pN1.upQuantity();
        AutoIncrease.increase(1);
        Game.decreaseResources(pN1.getCost());
        txtres.setText(Game.ToString());
        pN1.upCost();
        txtcostG1.setText(pN1.toString());
        checkButtons();
    }//GEN-LAST:event_btnbuyG1ActionPerformed

    private void txtcostG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcostG1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcostG1ActionPerformed

    private void btnbuyG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuyG2ActionPerformed
        pN2.upQuantity();
        AutoIncrease.increase(2);
        Game.decreaseResources(pN2.getCost());
        txtres.setText(Game.ToString());
        pN2.upCost();
        txtcostG2.setText(pN2.toString());
        checkButtons();
    }//GEN-LAST:event_btnbuyG2ActionPerformed

    private void txtcostG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcostG2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcostG2ActionPerformed

    private void btnbuyG3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuyG3ActionPerformed
        pN3.upQuantity();
        AutoIncrease.increase(3);
        Game.decreaseResources(pN3.getCost());
        txtres.setText(Game.ToString());
        pN3.upCost();
        txtcostG3.setText(pN3.toString());
        checkButtons();
    }//GEN-LAST:event_btnbuyG3ActionPerformed

    private void txtcostG3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcostG3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcostG3ActionPerformed

    private void btndoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoubleActionPerformed
        ManualIncrease.doubleIncrement();
        btnIncrease.setText("+" + ManualIncrease.incrementAmount);
    }//GEN-LAST:event_btndoubleActionPerformed
    public static void updateCall(int increase){
        Game.increaseResources(increase);
        txtres.setText(Game.ToString());
        checkButtons();
    }
    private static void checkButtons (){
        if (Game.getRes() >= pN1.getCost()) btnbuyG1.setEnabled (true);
        else btnbuyG1.setEnabled (false);
        if (Game.getRes() >= pN2.getCost()) btnbuyG2.setEnabled (true);
        else btnbuyG2.setEnabled (false);
        if (Game.getRes() >= pN3.getCost()) btnbuyG3.setEnabled (true);
        else btnbuyG3.setEnabled (false);
    }
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ISUgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ISUgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ISUgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ISUgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ISUgui().setVisible(true);
            }
        });
    }                  
    private javax.swing.JButton btnIncrease;
    private static javax.swing.JButton btnbuyG1;
    private static javax.swing.JButton btnbuyG2;
    private static javax.swing.JButton btnbuyG3;
    private static javax.swing.JButton btndouble;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtcostG1;
    private javax.swing.JTextField txtcostG2;
    private javax.swing.JTextField txtcostG3;
    private static javax.swing.JTextField txtres;
/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIncrease;
    private javax.swing.JButton btnbuyG1;
    private javax.swing.JButton btnbuyG2;
    private javax.swing.JButton btnbuyG3;
    private javax.swing.JButton btndouble;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtcostG1;
    private javax.swing.JTextField txtcostG2;
    private javax.swing.JTextField txtcostG3;
    private javax.swing.JTextField txtres;
    // End of variables declaration//GEN-END:variables
    */
}
